### ISSUE TITLE
[umls2obo] reverse is_a relationships

### ISSUE THREAD

**Issue by ArnaudFerre** [Bibliome/obo-utils#1]
The is_a relationships seems reversed after the umls2obo: the isa are more hasForChild.

For instance:
[Term]
id: C0556144
name: purine or derivative
synonym: "purines and derivatives" EXACT []
synonym: "purine or purine derivative (substance)" EXACT []
synonym: "purine or purine derivative" EXACT []
is_a: C0034136 ! nucleosides, purine
is_a: C0034137 ! nucleotides, purine
is_a: C0039771 ! theophyllin
is_a: C0041980 ! acid, uric
is_a: C0043314 ! xanthine
is_a: C0043315 ! xanthine or xanthine derivative
is_a: C0045643 ! 2,8-dihydroxyadenine
is_a: C0066447 ! methylxanthines
is_a: C0220903 ! purines
is_a: C0935936 ! urates
is_a: C1630404 ! purine derivative diuretic

and the correct in the UMLS should be:

[Term]
id: C1630404
name: purine derivative diuretic
synonym: "purine derivative diuretic (substance)" EXACT []
is_a: C0556144 ! purine or derivative
is_a: C0012798 ! diuretic

**Comment by rbossy** [comment]
The relation `(C0556144 isa C1630404)` is in fact asserted in SNOMED_CT. If it is not relevant there's little `umls2obo.py` can do about it...

**Comment by rbossy** [comment]
@ArnaudFerre 
In the example, is the C1630404-C0556144 relation the only one inverted? Or all superclasses listed should be children of C0556144?

**Comment by ArnaudFerre** [comment]
@rbossy my example was certainly not the best, but I think that all superclasses listed should be children of their current concept.
A better example:
id: C2720507
name: snomed ct concept (snomed rt+ctv3)
synonym: "snomed ct concept" EXACT []
is_a: C0012634 ! diseases
is_a: C0013227 ! preparations, pharmaceutical
is_a: C0029235 ! organisms
is_a: C0037088 ! symptoms and signs
is_a: C0037414 ! environment, social
is_a: C0184661 ! interventional procedures
is_a: C0332280 ! linkage concept
is_a: C0336996 ! physical force
is_a: C0347997 ! physical objects
is_a: C0370003 ! specimens
is_a: C0420206 ! situation with explicit context
is_a: C0432488 ! staging and scales
is_a: C0439861 ! substances
is_a: C0441471 ! {event}
is_a: C0449234 ! concept attribute
is_a: C0586399 ! environment or geographical location
is_a: C1268086 ! body structures
is_a: C1285164 ! qualifier value
is_a: C1285578 ! observable entity
is_a: C1298232 ! special concept
is_a: C1689941 ! record artefact
is_a: C3540689 ! snomed ct model component (metadata)

And after that, C0439861 ! substances is_a C0220806 ! chemical, which is_a C0001128 ! acid, which is_a C0302921 ! strong acids, and so on!

**Comment by rbossy** [comment]
Fixed in 4b96f94a4ae16fdf5e95cce0a2037713dbbad477
